/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hxl_plugin_springboot_invoke_utils_file_NativeWindowDialogUtils */

#ifndef _Included_com_hxl_plugin_springboot_invoke_utils_file_NativeWindowDialogUtils
#define _Included_com_hxl_plugin_springboot_invoke_utils_file_NativeWindowDialogUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hxl_plugin_springboot_invoke_utils_file_NativeWindowDialogUtils
 * Method:    openFileSelectDialog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hxl_plugin_springboot_invoke_utils_file_NativeWindowDialogUtils_openFileSelectDialog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
